name: Test
on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  build:
    name: Teste
    runs-on: ubuntu-latest
    steps:
      - name: Unity - Builder 🔨
        uses: game-ci/unity-builder@v2.0-aplha-5
        with:
          unityVersion: 2020.2.1f1
          targetPlatform: StandaloneWindows64
          kubeVolumeSize: 8Gi
      - name: List directory
        shell: powershell
        run: |
          ls 